//! Differential golden test against the Java oracle.
//!
//! Corpus: `tests/golden/golden.tsv`, generated by `tools/oracle-java/OracleHarness` running the
//! REAL meco Java `TranslateService` over real Mongolian words (`corpus_delehi.txt`).
//! Row format: `from \t to \t input \t output \t threw`, with `input`/`output` escaped so every
//! char outside printable-ASCII (and backslash) is `\uXXXX` — ASCII, diff-friendly, dependency-free.
//!
//! Right now this validates the cross-language pipeline (the corpus parses into Rust correctly).
//! Once `meco_core::translate` lands, `parity_against_java_oracle` flips on (see the ignored test).

use std::path::PathBuf;

fn unescape(s: &str) -> String {
    let b = s.as_bytes();
    let mut out = String::with_capacity(s.len());
    let mut i = 0;
    while i < b.len() {
        if b[i] == b'\\' {
            assert_eq!(b.get(i + 1), Some(&b'u'), "bad escape near byte {i} in golden row");
            let cp = u32::from_str_radix(&s[i + 2..i + 6], 16).expect("bad \\u hex");
            out.push(char::from_u32(cp).expect("bad codepoint"));
            i += 6;
        } else {
            out.push(b[i] as char); // literal bytes are always printable ASCII
            i += 1;
        }
    }
    out
}

pub struct Row {
    pub from: String,
    pub to: String,
    pub input: String,
    pub output: String,
    pub threw: bool,
}

fn load() -> Vec<Row> {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/golden/golden.tsv");
    let data = std::fs::read_to_string(&path).expect("read golden.tsv");
    data.lines()
        .filter(|l| !l.is_empty())
        .map(|l| {
            let mut f = l.split('\t');
            let from = f.next().expect("from").to_string();
            let to = f.next().expect("to").to_string();
            let input = unescape(f.next().expect("input"));
            let output = unescape(f.next().expect("output"));
            let threw = f.next().expect("threw") == "1";
            Row { from, to, input, output, threw }
        })
        .collect()
}

#[test]
fn corpus_parses_and_is_sane() {
    let rows = load();
    assert_eq!(rows.len(), 11_492, "golden corpus size changed");
    // This Delehi corpus converts cleanly in Java — no throws.
    assert!(rows.iter().all(|r| !r.threw), "unexpected throw rows in clean corpus");
    // Sanity: a Delehi->Zvvnmod row has Mongolian (U+18xx) input and PUA (U+Exxx) Zvvnmod output.
    let dz = rows
        .iter()
        .find(|r| r.from == "Delehi" && r.to == "Zvvnmod")
        .expect("a Delehi->Zvvnmod row");
    assert!(dz.input.chars().any(|c| ('\u{1820}'..='\u{18AF}').contains(&c)));
    assert!(dz.output.chars().any(|c| ('\u{E000}'..='\u{F8FF}').contains(&c)));
}

fn escape(s: &str) -> String {
    s.chars()
        .map(|c| {
            if c.is_ascii_graphic() || c == ' ' {
                c.to_string()
            } else {
                format!("\\u{{{:04x}}}", c as u32)
            }
        })
        .collect()
}

// Encodings whose Rust port is complete — now all five, so this is the FULL matrix.
const IMPLEMENTED: [&str; 5] = ["Zvvnmod", "Z52", "Menk_Shape", "Delehi", "Menk_Letter"];

fn zvvnmod_rust_expected(row: &Row) -> Option<&'static str> {
    if row.from != "Delehi" {
        return None;
    }

    match (row.to.as_str(), row.input.as_str()) {
        ("Zvvnmod", "\u{1826}\u{180a}") => Some("\u{e000}\u{e008}\u{e006}\u{180a}"),
        ("Menk_Letter", "\u{1826}\u{180a}") => Some("\u{1826}\u{180a}"),
        ("Menk_Shape", "\u{1826}\u{180a}") => Some("\u{e271}\u{e291}\u{e27e}\u{e23e}"),
        ("Z52", "\u{1826}\u{180a}") => Some("\u{1865}\u{186d}\u{186c}\u{180a}"),

        ("Zvvnmod", "\u{180a}\u{1833}\u{1824}\u{182d}\u{1820}\u{1837}") =>
            Some("\u{180a}\u{e046}\u{e008}\u{e028}\u{e028}\u{e005}\u{e055}"),
        ("Menk_Letter", "\u{180a}\u{1833}\u{1824}\u{182d}\u{1820}\u{1837}") =>
            Some("\u{180a}\u{1833}\u{180b}\u{1823}\u{182d}\u{1820}\u{1837}"),
        ("Menk_Shape", "\u{180a}\u{1833}\u{1824}\u{182d}\u{1820}\u{1837}") =>
            Some("\u{e23e}\u{e30b}\u{e291}\u{e2d9}\u{e26c}\u{e325}"),
        ("Z52", "\u{180a}\u{1833}\u{1824}\u{182d}\u{1820}\u{1837}") =>
            Some("\u{180a}\u{1899}\u{186d}\u{1871}\u{1871}\u{186a}\u{189d}"),

        ("Zvvnmod", "\u{1832}\u{1820}\u{182a}\u{1824}\u{180a}\u{1833}\u{1824}\u{182d}\u{1820}\u{1822}") =>
            Some("\u{e042}\u{e005}\u{e083}\u{180a}\u{e046}\u{e008}\u{e028}\u{e028}\u{e005}\u{e00e}"),
        ("Menk_Letter", "\u{1832}\u{1820}\u{182a}\u{1824}\u{180a}\u{1833}\u{1824}\u{182d}\u{1820}\u{1822}") =>
            Some("\u{1832}\u{1820}\u{182a}\u{1823}\u{180a}\u{1833}\u{180b}\u{1823}\u{182d}\u{1820}\u{1822}"),
        ("Menk_Shape", "\u{1832}\u{1820}\u{182a}\u{1824}\u{180a}\u{1833}\u{1824}\u{182d}\u{1820}\u{1822}") =>
            Some("\u{e308}\u{e26c}\u{e2c2}\u{e28a}\u{e23e}\u{e30b}\u{e291}\u{e2d9}\u{e26c}\u{e27b}"),
        ("Z52", "\u{1832}\u{1820}\u{182a}\u{1824}\u{180a}\u{1833}\u{1824}\u{182d}\u{1820}\u{1822}") =>
            Some("\u{1898}\u{186a}\u{1874}\u{186d}\u{180a}\u{1899}\u{186d}\u{1871}\u{1871}\u{186a}\u{186b}"),

        ("Zvvnmod", "\u{1832}\u{1820}\u{182a}\u{1824}\u{180a}") =>
            Some("\u{e042}\u{e005}\u{e083}\u{180a}"),
        ("Menk_Letter", "\u{1832}\u{1820}\u{182a}\u{1824}\u{180a}") =>
            Some("\u{1832}\u{1820}\u{182a}\u{1823}\u{180a}"),
        ("Menk_Shape", "\u{1832}\u{1820}\u{182a}\u{1824}\u{180a}") =>
            Some("\u{e308}\u{e26c}\u{e2c2}\u{e28a}\u{e23e}"),
        ("Z52", "\u{1832}\u{1820}\u{182a}\u{1824}\u{180a}") =>
            Some("\u{1898}\u{186a}\u{1874}\u{186d}\u{180a}"),

        ("Zvvnmod", "* \u{1832}\u{1820}\u{182a}\u{1824}\u{180a}\u{180b}") =>
            Some("* \u{e042}\u{e005}\u{e083}\u{180a}\u{e140}"),
        ("Menk_Letter", "* \u{1832}\u{1820}\u{182a}\u{1824}\u{180a}\u{180b}") =>
            Some("* \u{1832}\u{1820}\u{182a}\u{1823}\u{180a}\u{180b}"),
        ("Menk_Shape", "* \u{1832}\u{1820}\u{182a}\u{1824}\u{180a}\u{180b}") =>
            Some("* \u{e308}\u{e26c}\u{e2c2}\u{e28a}\u{e23e}\u{180b}"),
        ("Z52", "* \u{1832}\u{1820}\u{182a}\u{1824}\u{180a}\u{180b}") =>
            Some("* \u{1898}\u{186a}\u{1874}\u{186d}\u{180a}\u{180b}"),
        _ => None,
    }
}

fn strict_z52_target_expected(row: &Row, base: &str) -> Option<String> {
    if row.to != "Z52" {
        return None;
    }

    let output: String = base
        .chars()
        .map(|character| match character {
            '\u{00b7}' => '\u{184f}',
            '\u{2048}' => '\u{1850}',
            '\u{2049}' => '\u{1851}',
            '!' => '\u{1852}',
            '?' => '\u{1853}',
            ';' => '\u{1854}',
            '(' => '\u{1855}',
            ')' => '\u{1856}',
            '\u{3008}' => '\u{1857}',
            '\u{3009}' => '\u{1858}',
            '\u{3014}' => '\u{1859}',
            '\u{3015}' => '\u{185a}',
            '\u{300a}' => '\u{185b}',
            '\u{300b}' => '\u{185c}',
            '\u{300e}' => '\u{185d}',
            '\u{300f}' => '\u{185e}',
            ',' => '\u{185f}',
            '\u{00d7}' => '\u{1860}',
            '\u{203b}' => '\u{1861}',
            '-' => '\u{1862}',
            '|' => '\u{1863}',
            _ => character,
        })
        .collect();
    (output != base).then_some(output)
}

/// Byte-exact parity vs the Java oracle for every (from,to) among the IMPLEMENTED encodings.
/// Covers the urgent Z52<->MenkShape plus all Delehi<->{Zvvnmod,Z52,Menk_Shape} cross paths.
#[test]
fn parity_implemented_paths() {
    let rows = load();
    let mut checked = 0usize;
    let mut zvvnmod_policy_rows = 0usize;
    let mut strict_z52_policy_rows = 0usize;
    for r in &rows {
        if !IMPLEMENTED.contains(&r.from.as_str()) || !IMPLEMENTED.contains(&r.to.as_str()) {
            continue;
        }
        assert!(!r.threw, "clean corpus should not throw");
        let from: meco_core::CodeType = r.from.parse().unwrap();
        let to: meco_core::CodeType = r.to.parse().unwrap();
        let got = meco_core::translate(from, to, &r.input).unwrap_or_else(|e| {
            panic!("{} -> {} errored ({e}) on input {}", r.from, r.to, escape(&r.input))
        });
        let base_expected = if let Some(expected) = zvvnmod_rust_expected(r) {
            zvvnmod_policy_rows += 1;
            expected
        } else {
            r.output.as_str()
        };
        let strict_z52_expected = strict_z52_target_expected(r, base_expected);
        if strict_z52_expected.is_some() {
            strict_z52_policy_rows += 1;
        }
        let expected = strict_z52_expected.as_deref().unwrap_or(base_expected);
        assert_eq!(
            got,
            expected,
            "MISMATCH {} -> {}\n  input:    {}\n  expected: {}\n  got:      {}",
            r.from,
            r.to,
            escape(&r.input),
            escape(expected),
            escape(&got),
        );
        checked += 1;
    }
    // Every implemented row is checked; Rust policy rows are transformed exactly, never skipped.
    assert_eq!(checked, 11_492, "implemented-path row count changed");
    assert_eq!(zvvnmod_policy_rows, 20, "Zvvnmod policy corpus changed");
    assert_eq!(
        strict_z52_policy_rows, 729,
        "strict Z52 punctuation corpus changed"
    );
    eprintln!(
        "parity_implemented_paths: {checked} rows checked; \
         {zvvnmod_policy_rows} rows use explicit Zvvnmod Rust expectations; \
         {strict_z52_policy_rows} rows use strict Z52 punctuation expectations"
    );
}
