//! Differential golden test against the Java oracle.
//!
//! Corpus: `tests/golden/golden.tsv`, generated by `tools/oracle-java/OracleHarness` running the
//! REAL meco Java `TranslateService` over real Mongolian words (`corpus_delehi.txt`).
//! Row format: `from \t to \t input \t output \t threw`, with `input`/`output` escaped so every
//! char outside printable-ASCII (and backslash) is `\uXXXX` — ASCII, diff-friendly, dependency-free.
//!
//! Right now this validates the cross-language pipeline (the corpus parses into Rust correctly).
//! Once `meco_core::translate` lands, `parity_against_java_oracle` flips on (see the ignored test).

use std::path::PathBuf;

fn unescape(s: &str) -> String {
    let b = s.as_bytes();
    let mut out = String::with_capacity(s.len());
    let mut i = 0;
    while i < b.len() {
        if b[i] == b'\\' {
            assert_eq!(b.get(i + 1), Some(&b'u'), "bad escape near byte {i} in golden row");
            let cp = u32::from_str_radix(&s[i + 2..i + 6], 16).expect("bad \\u hex");
            out.push(char::from_u32(cp).expect("bad codepoint"));
            i += 6;
        } else {
            out.push(b[i] as char); // literal bytes are always printable ASCII
            i += 1;
        }
    }
    out
}

pub struct Row {
    pub from: String,
    pub to: String,
    pub input: String,
    pub output: String,
    pub threw: bool,
}

fn load() -> Vec<Row> {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/golden/golden.tsv");
    let data = std::fs::read_to_string(&path).expect("read golden.tsv");
    data.lines()
        .filter(|l| !l.is_empty())
        .map(|l| {
            let mut f = l.split('\t');
            let from = f.next().expect("from").to_string();
            let to = f.next().expect("to").to_string();
            let input = unescape(f.next().expect("input"));
            let output = unescape(f.next().expect("output"));
            let threw = f.next().expect("threw") == "1";
            Row { from, to, input, output, threw }
        })
        .collect()
}

#[test]
fn corpus_parses_and_is_sane() {
    let rows = load();
    assert!(rows.len() > 10_000, "expected >10k golden rows, got {}", rows.len());
    // This Delehi corpus converts cleanly in Java — no throws.
    assert!(rows.iter().all(|r| !r.threw), "unexpected throw rows in clean corpus");
    // Sanity: a Delehi->Zvvnmod row has Mongolian (U+18xx) input and PUA (U+Exxx) Zvvnmod output.
    let dz = rows
        .iter()
        .find(|r| r.from == "Delehi" && r.to == "Zvvnmod")
        .expect("a Delehi->Zvvnmod row");
    assert!(dz.input.chars().any(|c| ('\u{1820}'..='\u{18AF}').contains(&c)));
    assert!(dz.output.chars().any(|c| ('\u{E000}'..='\u{F8FF}').contains(&c)));
}

fn escape(s: &str) -> String {
    s.chars()
        .map(|c| {
            if c.is_ascii_graphic() || c == ' ' {
                c.to_string()
            } else {
                format!("\\u{{{:04x}}}", c as u32)
            }
        })
        .collect()
}

// Encodings whose Rust port is complete — now all five, so this is the FULL matrix.
const IMPLEMENTED: [&str; 5] = ["Zvvnmod", "Z52", "Menk_Shape", "Delehi", "Menk_Letter"];

/// Byte-exact parity vs the Java oracle for every (from,to) among the IMPLEMENTED encodings.
/// Covers the urgent Z52<->MenkShape plus all Delehi<->{Zvvnmod,Z52,Menk_Shape} cross paths.
#[test]
fn parity_implemented_paths() {
    let rows = load();
    let mut checked = 0usize;
    for r in &rows {
        if !IMPLEMENTED.contains(&r.from.as_str()) || !IMPLEMENTED.contains(&r.to.as_str()) {
            continue;
        }
        assert!(!r.threw, "clean corpus should not throw");
        let from: meco_core::CodeType = r.from.parse().unwrap();
        let to: meco_core::CodeType = r.to.parse().unwrap();
        let got = meco_core::translate(from, to, &r.input).unwrap_or_else(|e| {
            panic!("{} -> {} errored ({e}) on input {}", r.from, r.to, escape(&r.input))
        });
        assert_eq!(
            got,
            r.output,
            "MISMATCH {} -> {}\n  input:    {}\n  expected: {}\n  got:      {}",
            r.from,
            r.to,
            escape(&r.input),
            escape(&r.output),
            escape(&got),
        );
        checked += 1;
    }
    // All five encodings are implemented, so this now covers the entire corpus (all 11,492 rows).
    assert!(checked > 11000, "expected >11000 implemented-path rows, got {checked}");
    eprintln!("parity_implemented_paths: {checked} rows matched the Java oracle byte-exact");
}
